### PR TITLE
Update deps + rename options for clarity

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
I updated the dependencies (again) since, among others, the main reshape module was updated.

I also renamed the `defaultTag` and `skipTags` options to `replacementTag` and `additionalTags` respectively. I feel like those names convey the actually meaning of these options better.

There are some features I need for my use case that I'm going to try and add myself. I will of course create PR's for those (although you shouldn't feel obligated to merge them), but since these (mini) changes could create (big) conflicts I'd love to hear if you're actually approving them before I continue.

### CODE REVIEW

**Comment by HoldYourWaffle** [comment]
Woops I forgot that this is obviously a breaking change. Perhaps it wasn't the best idea to do this kind of stuff at 1 AM....

There are 3 solutions to this:
- Drop the PR
- Fall back to the old options
- Release a new major version

I created a new commit that adds the fallback behavior (including a test) as I feel like that's the best option, but it's up to you.

**Comment by jescalan** [comment]
Could we split this into two pull requests? One to update deps, and one to rename the options - that would make more sense for me 😁

**Comment by HoldYourWaffle** [comment]
I could, but the option renaming is included (and superseded) in #23, so creating another PR for that wouldn't make sense.
I'll just revert the changes that are not dependency related.

**Comment by HoldYourWaffle** [comment]
Hold on the dependency stuff is also included in #23, so that wouldn't make sense either.
Shall I just close this so we can decide everything there?

**Comment by jescalan** [comment]
Yep!

**Comment by HoldYourWaffle** [comment]
Did it, and also posted an (admittedly pretty long) response in #23.

**Pull request closed without merging**
