### PR TITLE
Some additional features

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
I decided to break the ice and make my first actual contribution to the reshape ecosystem, I hope you'll find it useful.
**Note**: this PR is based on #22

### Things I added/changed
- TypeScript definitions (they were easy for this one)
- Custom tag ↔ replacement tag map in the options
- Locally override the default replacement tag
- I moved the HTML in the README into it's own (syntax highlighted) section to improve readability

The [edited README](https://github.com/HoldYourWaffle/reshape-custom-elements/blob/additional-features/README.md) should provide all the information you need on how these features work.

### Comments/concerns I have
- `reshapeCustomElements(..)` is defined as returning a plain `Function` for now since I haven't added definitions for the core reshape package yet.
- My README edits could probably be worded better, but I'm too tired to figure out how.
- The possibility to locally override the replaced tag may not seem like a useful feature at first (since we're typing both the class an tag name again), but in my opinion it helps convey *semantic* meaning rather than *syntactical* meaning when editing templates since the name is the most obvious part of an element/tag.
- I'm not sure how I'm supposed to handle multiple attribute values with the local-overriding, I just used the first one in the array.
- pretty-quick is being a bit weird, are you sure this is how you want it to be formatted?
- Maybe a different default attribute name for local overriding?
- Maybe a shorter option name for changing the local overriding attribute?
- The `replacementTag` option (#22) should probably be renamed to `defaultReplacementTag`, which would make #22 obsolete.

### CODE REVIEW

**Comment by HoldYourWaffle** [comment]
Side note: I'm pretty sure #16 - #21 can be closed and the spammy `greenkeeper/` branches removed.

**Comment by HoldYourWaffle** [comment]
I ran into problems when pre-processing my templates (stuff like `if` from `reshape-expressions` getting replaced), so I added an option to ignore reshape ecosystem tags.

**Comment by jescalan** [comment]
This is amazing - I will get you a really thorough response to this and your other issue soon!

**Comment by HoldYourWaffle** [comment]
Good to know my work is being appreciated!
In the meantime I added a generic blacklist, no idea why I didn't think of that before...

**Comment by jescalan** [comment]
Ok, some high level feedback first:

This is a really large, enormously breaking change. That is fine, and overall the changes are great, but typically before embarking on a journey like this, it's a good idea to do a writeup first. Many organizations refer to these as [RFCs](https://en.wikipedia.org/wiki/Request_for_Comments), but really the naming convention is flexible. In general, writing a little piece on the intended changes and rationale behind them allows anyone interested in the project to be able to understand and give feedback on the direction, ultimately reaching a consensus before anyone starts actually implementing code. For this large of a change, this would have been a more appropriate first step.

Anyway, the readme is here and serves as sort of an RFC, so let's walk through it and talk about some of the changes.

1. I am ok with changing the option names, we would just need to release as a major version. I feel like your changes in terminology are good, so I support this.
2. Some of the added options like `additionalTags`, `blacklist`, and `replacementTagOverrideAttribute` are features that make sense to me, but I wonder if there is a real-world use case for any of them. Have you run into a situation where you need to leverage these features? I haven't, and I haven't had anyone ask for them either. With API design, things like this are difficult. In one sense, you want to provide a range of configuration options that you feel will be useful to your user base, but on the other hand, you also don't want to go too far overboard adding options and code out of pure speculation that someone may find them useful someday. I typically shade a bit more toward the angle of adding options only when the use case is super clear and common, or I specifically need it right now. Anything that's on the edge, I tend to leave discussion of its implementation until/if someone needs it.
3. I don't feel like the `replaceEcosystemTags` option is sustainable over time. Additionally, I don't see a use case for it. Simply ordering this plugin after the other 'ecosystem' plugins would achieve the same effect.

Also just as a note, this plugin is really more of a toy plugin -- its actual use cases are very limited, and is more here to serve as a quick, simple example of how reshape plugins work. A much better approach to building out components would be to use reshape's react plugin, or actual web components. So I'm also not really sure how far it's worth taking changes and improvements to this plugin in general given its very limited usage and the complete lack of feature requests or bug tickets in overall.

**Comment by HoldYourWaffle** [comment]
Just want to say upfront that if you're simply not interested then that's fine too, I mostly made these changes because I needed them (more on that later).

## A broken down response
> This is a really large, enormously breaking change.

Is it? I'm not sure what this would break, except for the input options (which I added fallbacks for).
<br>

>  That is fine, and overall the changes are great, but typically before embarking on a journey like this, it's a good idea to do a writeup first

I'm planning to do this for other features I want to add (some in different plugins), but the changes I made here were so trivial and straightforward that I didn't feel like it was necessary. 
<br>

> I am ok with changing the option names, we would just need to release as a major version. I feel like your changes in terminology are good, so I support this.

Do you think `replacementTag` should be changed to `defaultReplacementTag` now that there are overriding options?

<br>

> In general, writing a little piece on the intended changes and rationale behind them allows anyone interested in the project to be able to understand and give feedback on the direction, ultimately reaching a consensus before anyone starts actually implementing code. For this large of a change, this would have been a more appropriate first step.

I definitely agree, but as I said before these changes were very trivial to make (each commit took about 5-10 minutes depending on how distracted I was). Creating a write-up would've been harder and a lot slower (English is not my native language) than just implementing the code and updating the readme.

<br>

> Some of the added options like additionalTags, blacklist, and replacementTagOverrideAttribute are features that make sense to me, but I wonder if there is a real-world use case for any of them. Have you run into a situation where you need to leverage these features? I haven't, and I haven't had anyone ask for them either.

Well there's a first time for anything 😉 
I didn't add the `additionalTags` option, I just renamed it from `skipTags` because it's literally doing the opposite of skipping tags. As for `blacklist`: I haven't personally used it yet, but I added it as a more generic version of `replaceEcosystemTags` (more on that later). `replacementTagOverrideAttribute` was the reason I actually started making these changes together with `replacementTagMap`, it fits my use-case very well (more on that later too).

<br>

> I typically shade a bit more toward the angle of adding options only when the use case is super clear and common, or I specifically need it right now. Anything that's on the edge, I tend to leave discussion of its implementation until/if someone needs it.

In my case I specifically needed these options right now (which is why is part of the reason why I just dived in instead of a proper feature request/RFC).

<br>

> I don't feel like the replaceEcosystemTags option is sustainable over time.

I agree. Like 2 minutes after I implemented it I realized I could just create a generic blacklist which would do the job just as good. I'll remove that specific commit.

<br>

> Additionally, I don't see a use case for it. Simply ordering this plugin after the other 'ecosystem' plugins would achieve the same effect.

I do, which is why I added it 😉 I'll describe my use case for it soon.

<br>

> Also just as a note, this plugin is really more of a toy plugin -- its actual use cases are very limited, and is more here to serve as a quick, simple example of how reshape plugins work.

I was skeptic about it's usefulness at first too (when I first discovered reshape), but it actually works very well for my use case.

<br>

> A much better approach to building out components would be to use reshape's react plugin, or actual web components.

I'm not really using this for building 'components', and react/web components would be complete overkill in my case.

<br>

> So I'm also not really sure how far it's worth taking changes and improvements to this plugin in general given its very limited usage and the complete lack of feature requests or bug tickets in overall.

I don't see how a project being "unpopular" would be a deterring factor for improving it, especially when the changes are as useful yet trivial as these. I agree that you shouldn't spend hours in improving something nobody uses, but these changes were very quick (it has taken me a lot longer to write this response than to write the code, although that could just be my perfectionism combined with non-native English).



## At last, my use case
My use case roughly consists of 3 parts. If you're thinking:
> Wow this guy is an idiot, you could just do *x* and *y* to do the same thing way more easily

Please, feel free to tell me 😉

### Pre-processing
First part is pre-processing, by which I mean compiling my HTML templates during my webpack build. This is the reason why I need the `blacklist`/`replaceEcosystemTags` option, I obviously can't run `reshape-expressions` at 'build' time, or worded another way: I **can't** put this plugin after it. It's not hard to imagine that without `blacklist` or `replaceEcosystemTags` this messes up some tags.
I could tell you why I want to pre-process my templates, but don't think it's of much use to this discussion for now (other than maybe giving you the chance to point out a very easy and obvious solution that I missed).

### Bootstrap
This is the main reason why I'm using this plugin. In case you've been living under a rock (or only doing back-end stuff), [this is what the code looks like](https://www.w3schools.com/bootstrap4/tryit.asp?filename=trybs_template1).
As you can see there are tons of different classes which now serve as the 'building blocks' of your application, for a large part taking over the function of the actual tags (at least that's how I see it). A lot of classes should be used with specific tag names, which further increases redundancy. This redundancy led me to this plugin. I can now (with the added `replacementTagMap`) define my "bootstrap structure" a lot easier, with less redundancy, less room for error and clearer semantic meaning. Having a tag `<navbar>` works a lot better than `<nav class="navbar">` in my opinion, and that's probably on of the least redundant tags out there.

If you know a better way to do this I'd love to hear, but that's where the third part of my use case comes in:

### Inexperienced team members
I'm using this for a school project. I'm working together with two additional team members who unfortunately are not that experienced in either web design or programming. Since this project has a (pretty close) deadline it's important that we can work fast and efficiently and most importantly without overwhelming the less experienced. This plugin is very simple and way easier to pick up for them than say web components or react. (It's also a *lot* lighter weight which is very welcome in getting it to run on school computers.)

I know this isn't really a valid 'use case', but it limits my choices of more sophisticated options.

<br><br>

Writing such a long response reminds me of how slow I can be when it comes to writing English. I hope you'll at least understand my use case better now.

**Comment by jescalan** [comment]
Ok cool, this is helpful. I support this set of changes then, so long as we remove the "reshape ecosystem tags" options, since I do not see that as sustainable, and the same functionality can be achieved using your blacklist if I'm not mistaken

**Comment by HoldYourWaffle** [comment]
I 100% agree, about 5 minutes after I created that feature I remembered I could just create a generic blacklist. Apparently I forgot to remove it.
I have rebased & force-pushed my branch, so in principle this is ready to merge.

I do have one concern left though. The current `replacementMap` format looks like this:
```json
{
	"nav-tabs": "ul",
	"navbar-brand": "a",
	"navbar-toggler": "button",
	"navbar-toggler-icon": "span",
	"navbar-nav": "ul",
	"nav-item": "li",
	"nav-link": "a",
	"btn": "button",
	"dropdown-toggle": "a",
	"dropdown-item": "a",
	"badge": "span"
}
```

As you can see there's a lot of redundant tag names in there and it's not the most readable format. I suggest I change the format to something like this:

```json
{
	"ul": [
		"nav-tabs",
		"navbar-nav"
	],
	
	"a": [
		"navbar-brand",
		"nav-link",
		"dropdown-toggle",
		"dropdown-item"
	],
	
	"button": [
		"navbar-toggler",
		"btn"
	],
	
	"span": [
		"navbar-toggler-icon",
		"badge"
	],
	
	"li": [
		"nav-item"
	]
}
```

Using a simple function I can transform this new format back to a simple lookup map for performance reasons.

**Comment by HoldYourWaffle** [comment]
I implemented the new map format and so far it's been much more pleasant to use.

I also added inference of `additionalTags` based on `replacementTagMap`. This saves duplicate configuration (which could easily lead to mistakes) and has so far worked really great for me.

**Comment by jescalan** [comment]
Just published as `reshape-custom-elements@1.0.0`

**Pull request merged**
